return {
  -- "zbirenbaum/copilot.lua",
  -- cmd = "Copilot",
  -- build = ":Copilot auth",
  -- event = "InsertEnter",
  -- opts = {
  --   suggestion = {
  --     enabled = true,
  --     auto_trigger = true,
  --     keymap = {
  --       accept = "<M-l>",
  --       accept_word = false,
  --       accept_line = false,
  --       next = "<M-]>",
  --       prev = "<M-[>",
  --       dismiss = "<C-]>",
  --     },
  --   },
  --   panel = {
  --     enabled = true,
  --     autor_refresh = true,
  --     keymap = {
  --       jump_prev = "[[",
  --       jump_next = "]]",
  --       accept = "<CR>",
  --       refresh = "gr",
  --       open = "<M-CR>",
  --     },
  --     layout = {
  --       position = "bottom", -- | top | left | right
  --       ratio = 0.4,
  --     },
  --   },
  --   filetypes = {
  --     markdown = true,
  --     help = true,
  --   },
  --   copilot_node_command = "node", -- Node.js version must be > 16.x
  -- },
}
